name: pino test
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: code download
        uses: actions/checkout@v4

      - name: show files
        run: ls -r
        
      - name: magari reading
        run: cat magari.txt

      - name: Ejecutar mi script bash
        run: bash script.sh
        
      - name: Saludo para todos
        run: echo "Este mensaje lo ve cualquiera."

      - name: Saludo exclusivo
        # Usamos 'if' para decidir si este paso corre o se salta
        if: github.actor == 'JeSunsJs' # <--- CAMBIA ESTO por tu nombre de usuario
        run: echo "Hola, Jefe. Solo tú puedes ver este paso ejecutado."

