name: pino test
on: [push]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: code download
        uses: actions/checkout@v4

      - name: show files
        run: ls -r
        
      - name: magari reading
        run: cat magari.txt

      - name: Ejecutar mi script bash
        run: bash script.sh

